version: "3.2"
services:
  app:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - backend
    ports:
      - '3000:3000'
    container_name: ayo_drc_nodejs
  postgres:
    restart: always
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5433:5432"
    networks:
      - backend
    container_name: ayo_drc_db
networks:
  backend: